INSERT INTO SEQUENCE_GENERATOR VALUES ('PageImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('PageFieldImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('CountrySubdivisionCategoryImpl', 1000);

INSERT INTO SEQUENCE_GENERATOR VALUES ('PageTemplateImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FieldDefinitionImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FieldEnumerationImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FieldEnumerationItemImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('StructuredContentImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('StructuredContentFieldImpl', 1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('StructuredContentRuleImpl',1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('StructuredContentTypeImpl',1000);
INSERT INTO SEQUENCE_GENERATOR VALUES ('FieldGroupImpl', 1000);