DROP TABLE SEQUENCE_GENERATOR;

CREATE TABLE SEQUENCE_GENERATOR
(
  ID_NAME VARCHAR2(255) NOT NULL,
  ID_VAL NUMBER(19,0),
  CONSTRAINT PK_SEQUENCE_GENERATOR PRIMARY KEY(ID_NAME) USING INDEX TABLESPACE WEB_IDX1,
);
