-- Gift card images
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-29, -15000, -23003);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-30, -15001, -23003);
