-- Additional Sku images from load_catalog_data.sql
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-1, 10001, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-2, 10002, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-3, 10003, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-4, 20001, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-5, 20002, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-6, 20003, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-7, 30001, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-8, 30002, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-9, 30003, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-10, 40001, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-11, 40002, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-12, 40003, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-13, 50001, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-14, 50002, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-15, 50003, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-16, 60001, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-17, 60002, -23001);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-18, 60003, -23001);

-- Banner images from load_content_data.sql
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-19, -2000, -23002);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-20, -2001, -23002);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-21, -2002, -23002);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-22, -2003, -23002);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-23, -2004, -23002);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-24, -2005, -23002);

-- A few of the main product images from load_catalog_data.sql
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-25, 101, -999999);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-26, 102, -999999);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-27, 201, -999999);
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) VALUES (-28, 202, -999999);

-- Add the rest of the static assets to the "Unassigned" Folder
INSERT INTO BLC_ASSET_FOLDER_ITEM_XREF (ASSET_FOLDER_ITEM_XREF_ID, ASSET_ID, FOLDER_ID) SELECT STATIC_ASSET_ID, STATIC_ASSET_ID, -23000 FROM ( SELECT STATIC_ASSET_ID FROM BLC_STATIC_ASSET WHERE STATIC_ASSET_ID NOT IN ( SELECT STATIC_ASSET_ID FROM BLC_STATIC_ASSET a JOIN BLC_ASSET_FOLDER_ITEM_XREF b ON a.STATIC_ASSET_ID = b.ASSET_ID )) nonassigned;
