SET foreign_key_checks = 0;
set sql_mode = '';

DELETE FROM broadleafcommerce.BLC_ADMIN_USER;

LOAD DATA INFILE '@@BASE_DIR@@/admin_user.txt' 
INTO TABLE broadleafcommerce.BLC_ADMIN_USER
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(ADMIN_USER_ID , EMAIL   , LOGIN   , NAME    , PASSWORD);


DELETE FROM broadleafcommerce.BLC_ADMIN_ROLE;

LOAD DATA INFILE '@@BASE_DIR@@/admin_role.txt' 
INTO TABLE broadleafcommerce.BLC_ADMIN_ROLE
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(ADMIN_ROLE_ID , DESCRIPTION   ,  NAME);


DELETE FROM broadleafcommerce.BLC_ADMIN_PERMISSION;

LOAD DATA INFILE '@@BASE_DIR@@/admin_permission.txt' 
INTO TABLE broadleafcommerce.BLC_ADMIN_PERMISSION
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(ADMIN_PERMISSION_ID , DESCRIPTION   ,  NAME);


DELETE FROM broadleafcommerce.BLC_ADMIN_ROLE_PERMISSION_XREF;

LOAD DATA INFILE '@@BASE_DIR@@/admin_role_permission_xref.txt' 
INTO TABLE broadleafcommerce.BLC_ADMIN_ROLE_PERMISSION_XREF
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(ADMIN_ROLE_ID , ADMIN_PERMISSION_ID);


DELETE FROM broadleafcommerce.BLC_ADMIN_USER_ROLE_XREF;

LOAD DATA INFILE '@@BASE_DIR@@/admin_user_role_xref.txt' 
INTO TABLE broadleafcommerce.BLC_ADMIN_USER_ROLE_XREF
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(ADMIN_ROLE_ID , ADMIN_USER_ID);

