------------------------
-- DROP TABLE STATEMENTS
------------------------
DROP TABLE blc_address;
DROP TABLE blc_customer_address;
DROP TABLE blc_customer;
DROP TABLE blc_challenge_question;
DROP TABLE blc_country;


--------------------------
-- CREATE TABLE STATEMENTS
--------------------------
--------------------------
-- blc_challenge_question
--------------------------
CREATE TABLE blc_challenge_question
(
  QUESTION_ID NUMBER(19,0) NOT NULL,
  QUESTION VARCHAR2(255)
  CONSTRAINT PK_BLC_CHALLENGE_QUESTION PRIMARY KEY(QUESTION_ID) USING INDEX TABLESPACE WEB_IDX1
);

--------------------------
-- blc_customer
--------------------------
CREATE TABLE blc_customer
(
  CUSTOMER_ID NUMBER(19,0) NOT NULL,
  CHALLENGE_ANSWER VARCHAR2(255) ,
  CHALLENGE_QUESTION_ID NUMBER(19,0) ,
  EMAIL_ADDRESS VARCHAR2(255) ,
  FIRST_NAME VARCHAR2(255) ,
  LAST_NAME VARCHAR2(255) ,
  PASSWORD VARCHAR2(255) ,
  PASSWORD_CHANGE_REQUIRED NUMBER(1,0) ,
  USER_NAME VARCHAR2(255) ,
  RECEIVE_EMAIL NUMBER(1,0) ,
  IS_REGISTERED NUMBER(1,0) ,
  CONSTRAINT PK_BLC_CUSTOMER PRIMARY KEY(CUSTOMER_ID) USING INDEX TABLESPACE WEB_IDX1,
  CONSTRAINT FK_CUSTOMER_QUESTION FOREIGN KEY (CHALLENGE_QUESTION_ID) REFERENCES blc_challenge_question(QUESTION_ID)
);

CREATE UNIQUE INDEX IX1_BLC_CUSTOMER ON blc_customer (USER_NAME) USING INDEX TABLESPACE WEB_IDX1;

--------------------------
--------------------------
-- blc_address
CREATE TABLE blc_address
(
  ADDRESS_ID NUMBER(19,0) NOT NULL,
  ADDRESS_LINE1 VARCHAR2(255) ,
  ADDRESS_LINE2 VARCHAR2(255) ,
  CITY VARCHAR2(255) ,
  COUNTRY NUMBER(11,0) ,
  POSTAL_CODE VARCHAR2(255) ,
  STANDARDIZED NUMBER(1,0) ,
  STATE_PROV_REGION VARCHAR2(255) ,
  COUNTY VARCHAR2(255) ,
  TOKENIZED_ADDRESS VARCHAR2(255) ,
  ZIP_FOUR VARCHAR2(255) ,
  COMPANY_NAME VARCHAR2(255) ,
  IS_DEFAULT NUMBER(1,0) ,
  IS_ACTIVE NUMBER(1,0) ,
  IS_BUSINESS NUMBER(1,0) ,
  FIRST_NAME VARCHAR2(255) ,
  LAST_NAME VARCHAR2(255) ,
  PRIMARY_PHONE VARCHAR2(255) ,
  SECONDARY_PHONE VARCHAR2(255) ,
  VERIFICATION_LEVEL VARCHAR2(255) ,
  CONSTRAINT PK_BLC_CUSTOMER_ADDRESS PRIMARY KEY(ADDRESS_ID) USING INDEX TABLESPACE WEB_IDX1
);

--------------------------
-- blc_customer_address
--------------------------
CREATE TABLE blc_customer_address
(
  CUSTOMER_ADDRESS_ID NUMBER(19,0) NOT NULL,
  ADDRESS_NAME VARCHAR2(255) ,
  CUSTOMER_ID NUMBER(19,0) NOT NULL,
  ADDRESS_ID NUMBER(19,0) NOT NULL,
  CONSTRAINT PK_BLC_CUSTOMER_ADDRESS PRIMARY KEY(ADDRESS_ID) USING INDEX TABLESPACE WEB_IDX1,
  CONSTRAINT FK_CUSTOMER_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES blc_address(ADDRESS_ID)
);

--------------------------
-- blc_order
--------------------------
CREATE TABLE blc_order
(
  ORDER_ID NUMBER(19,0) NOT NULL,
  "TYPE" VARCHAR(255),
  CUSTOMER_ID NUMBER(19,0) NOT NULL,
  ORDER_STATUS NUMBER(19,0),
  CITY_TAX NUMBER(12,2),
  COUNTY_TAX NUMBER(12,2),
  STATE_TAX NUMBER(12,2),
  COUNTRY_TAX NUMBER(12,2),
  TOTAL_TAX NUMBER(12,2),
  ORDER_SUBTOTAL NUMBER(12,2),
  ORDER_TOTAL NUMBER(12,2),
  DATE_SUBMITTED DATE,
  DATE_CREATED DATE,
  CREATED_BY VARCHAR(255),
  DATE_UPDATED DATE,
  UPDATED_BY VARCHAR2(255),
  NAME VARCHAR2(255),
  CONSTRAINT PK_BLC_ORDER PRIMARY KEY(ORDER_ID) USING INDEX TABLESPACE WEB_IDX1,
  CONSTRAINT FK_ORDER_CUSTOMER_fk FOREIGN KEY (CUSTOMER_ID) REFERENCES blc_customer(CUSTOMER_ID)
);

--------------------------
-- blc_order_item
--------------------------
CREATE TABLE blc_order_item
(
  ORDER_ITEM_ID NUMBER(19,0) NOT NULL,
  SKU_ID NUMBER(19,0) NOT NULL,
  PRODUCT_ID NUMBER(19,0),
  CATEGORY_ID NUMBER(19,0),
  ORDER_ID NUMBER(19,0) NOT NULL,
  RETAIL_PRICE NUMBER(12,2),
  SALE_PRICE NUMBER(12,2),
  PRICE NUMBER(12,2),
  QUANTITY NUMBER(10,0),
  CONSTRAINT PK_BLC_ORDER_ITEM PRIMARY KEY(ORDER_ITEM_ID) USING INDEX TABLESPACE WEB_IDX1
);

--------------------------
-- blc_fulfillment_group
--------------------------
CREATE TABLE blc_fulfillment_group
(
  ID NUMBER(19,0) NOT NULL,
  ORDER_ID NUMBER(19,0) NOT NULL,
  REFERENCE_NUMBER VARCHAR(255),
  ADDRESS_ID NUMBER(19,0),
  PHONE_ID NUMBER(19,0),
  METHOD VARCHAR(255) NOT NULL,
  RETAIL_PRICE NUMBER(12,2),
  SALE_PRICE NUMBER(12,2),
  PRICE NUMBER(12,2),
  CITY_TAX NUMBER(12,2),
  COUNTY_TAX NUMBER(12,2),
  STATE_TAX NUMBER(12,2),
  COUNTRY_TAX NUMBER(12,2),
  TOTAL_TAX NUMBER(12,2),
  "TYPE" VARCHAR(255),
  QUANTITY NUMBER(10,0),
  CONSTRAINT PK_BLC_FULFILLMENT_GROUP PRIMARY KEY(ID) USING INDEX TABLESPACE WEB_IDX1
);

--------------------------
-- BLC_ID_GENERATION
--------------------------
CREATE TABLE BLC_ID_GENERATION
(
  ID_TYPE VARCHAR2(255) NOT NULL,
  BATCH_START NUMBER(19,0) ,
  BATCH_SIZE NUMBER(19,0) ,
  CONSTRAINT BLC_ID_GENERATION PRIMARY KEY(ID_TYPE) USING INDEX TABLESPACE WEB_IDX1
);

--------------------------
-- BLC_COUNTRY
--------------------------
CREATE TABLE BLC_COUNTRY
(
  ABBREVIATION VARCHAR2(2) NOT NULL,
  NAME VARCHAR2(255) ,
  CONSTRAINT PK_BLC_COUNTRY PRIMARY KEY(ABBREVIATION) USING INDEX TABLESPACE WEB_IDX1
);
------------------------
-- INSERT COUNTRIES
------------------------
INSERT INTO BLC_COUNTRY VALUES ( 'US', 'United States' );

------------------------
-- INSERT TEST CHALLENGE QUESTIONS
------------------------
INSERT INTO blc_challenge_question ( QUESTION_ID, QUESTION ) VALUES ( 1, 'What is your place of birth?' );;
INSERT INTO blc_challenge_question ( QUESTION_ID, QUESTION ) VALUES ( 2, 'What is your Mother''s maiden name?' );
INSERT INTO blc_challenge_question ( QUESTION_ID, QUESTION ) VALUES ( 3, 'What is the name of your favorite pet?' );

------------------------
-- INSERT TEST ID GENERATION
------------------------
INSERT INTO BLC_ID_GENERATION ( ID_TYPE, BATCH_START, BATCH_SIZE ) VALUES ( 'org.broadleafcommerce.profile.domain.Customer', 1, 10 );;


------------------------
-- INSERT SEQUENCE GENERATOR TABLE
------------------------
CREATE TABLE SEQUENCE_GENERATOR
(
   ID_NAME varchar2(255) PRIMARY KEY NOT NULL,
   ID_VAL decimal(19)
);
CREATE UNIQUE INDEX PK_SEQUENCE_GENERATOR ON SEQUENCE_GENERATOR(ID_NAME);

------------------------
-- INSERT SEQUENCE GENERATOR TABLE DATA
------------------------
INSERT INTO SEQUENCE_GENERATOR (ID_NAME,ID_VAL) VALUES ('CustomerImpl',1);
INSERT INTO SEQUENCE_GENERATOR (ID_NAME,ID_VAL) VALUES ('FulfillmentGroupImpl',1);
INSERT INTO SEQUENCE_GENERATOR (ID_NAME,ID_VAL) VALUES ('OrderImpl',1);
INSERT INTO SEQUENCE_GENERATOR (ID_NAME,ID_VAL) VALUES ('OrderItemImpl',1);

