SET foreign_key_checks = 0;
set sql_mode = '';

DELETE FROM broadleafcommerce.BLC_CATEGORY;

LOAD DATA INFILE '@@BASE_DIR@@/category.txt' 
INTO TABLE broadleafcommerce.BLC_CATEGORY
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(CATEGORY_ID, DESCRIPTION, DISPLAY_TEMPLATE, LONG_DESCRIPTION, NAME, URL, URL_KEY, DEFAULT_PARENT_CATEGORY_ID)
  SET ACTIVE_END_DATE = DATE_ADD(CURDATE(), INTERVAL 31 DAY),
  ACTIVE_START_DATE = CURDATE();

UPDATE broadleafcommerce.BLC_CATEGORY
SET DEFAULT_PARENT_CATEGORY_ID = null
WHERE DEFAULT_PARENT_CATEGORY_ID = 0;

DELETE FROM broadleafcommerce.BLC_PRODUCT;

LOAD DATA INFILE '@@BASE_DIR@@/product.txt' 
INTO TABLE broadleafcommerce.BLC_PRODUCT
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(PRODUCT_ID, DEFAULT_CATEGORY_ID, NAME, LONG_DESCRIPTION, @featured_product, IS_MACHINE_SORTABLE, WIDTH, HEIGHT, DEPTH, MANUFACTURE, MODEL, WEIGHT)
  SET ACTIVE_END_DATE = DATE_ADD(CURDATE(), INTERVAL 31 DAY),
	  ACTIVE_START_DATE = CURDATE(),      
	  IS_FEATURED_PRODUCT = CAST(@featured_product AS UNSIGNED);

DELETE FROM broadleafcommerce.BLC_CATEGORY_XREF;

LOAD DATA INFILE '@@BASE_DIR@@/category_xref.txt' 
INTO TABLE broadleafcommerce.BLC_CATEGORY_XREF
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(SUB_CATEGORY_ID, CATEGORY_ID, DISPLAY_ORDER);

DELETE FROM broadleafcommerce.BLC_CATEGORY_PRODUCT_XREF;

LOAD DATA INFILE '@@BASE_DIR@@/category_product_xref.txt' 
INTO TABLE broadleafcommerce.BLC_CATEGORY_PRODUCT_XREF
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(ID, PRODUCT_ID, CATEGORY_ID, DISPLAY_ORDER);

DELETE FROM broadleafcommerce.BLC_SKU;

LOAD DATA INFILE '@@BASE_DIR@@/sku.txt' 
INTO TABLE broadleafcommerce.BLC_SKU
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(SKU_ID, NAME, DESCRIPTION, RETAIL_PRICE, SALE_PRICE, TAXABLE_FLAG, DISCOUNTABLE_FLAG)
  SET ACTIVE_END_DATE = DATE_ADD(CURDATE(), INTERVAL 31 DAY),
  ACTIVE_START_DATE = CURDATE();

DELETE FROM broadleafcommerce.BLC_PRODUCT_SKU_XREF;

LOAD DATA INFILE '@@BASE_DIR@@/product_sku_xref.txt' 
INTO TABLE broadleafcommerce.BLC_PRODUCT_SKU_XREF
FIELDS TERMINATED BY '|' ENCLOSED BY ""; 

DELETE FROM broadleafcommerce.BLC_PRODUCT_ATTRIBUTE;

LOAD DATA INFILE '@@BASE_DIR@@/product_attribute.txt' 
INTO TABLE broadleafcommerce.BLC_PRODUCT_ATTRIBUTE
FIELDS TERMINATED BY '|' ENCLOSED BY "" 
(ID, PRODUCT_ID, NAME, VALUE, SEARCHABLE);

DELETE FROM broadleafcommerce.BLC_PRODUCT_IMAGE;

LOAD DATA INFILE '@@BASE_DIR@@/product_image.txt' 
INTO TABLE broadleafcommerce.BLC_PRODUCT_IMAGE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(PRODUCT_ID, URL, NAME);

DELETE FROM broadleafcommerce.SEQUENCE_GENERATOR;

LOAD DATA INFILE '@@BASE_DIR@@/sequence_generator.txt' 
INTO TABLE broadleafcommerce.SEQUENCE_GENERATOR
FIELDS TERMINATED BY '|' ENCLOSED BY "";

DELETE FROM broadleafcommerce.BLC_COUNTRY;

LOAD DATA INFILE '@@BASE_DIR@@/country.txt' 
INTO TABLE broadleafcommerce.BLC_COUNTRY
FIELDS TERMINATED BY '|' ENCLOSED BY "";

DELETE FROM broadleafcommerce.BLC_STATE;

LOAD DATA INFILE '@@BASE_DIR@@/state.txt' 
INTO TABLE broadleafcommerce.BLC_STATE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(NAME, ABBREVIATION, COUNTRY);

DELETE FROM broadleafcommerce.BLC_SHIPPING_RATE;

LOAD DATA INFILE '@@BASE_DIR@@/shipping_rate.txt' 
INTO TABLE broadleafcommerce.BLC_SHIPPING_RATE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(ID, FEE_TYPE, FEE_SUB_TYPE, FEE_BAND, BAND_UNIT_QTY, BAND_RESULT_QTY, BAND_RESULT_PCT);

DELETE FROM broadleafcommerce.BLC_CUSTOMER;

LOAD DATA INFILE '@@BASE_DIR@@/customer.txt' 
INTO TABLE broadleafcommerce.BLC_CUSTOMER
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PASSWORD_CHANGE_REQUIRED, RECEIVE_EMAIL, IS_REGISTERED);

DELETE FROM broadleafcommerce.BLC_CUSTOMER_PHONE;

LOAD DATA INFILE '@@BASE_DIR@@/customer_phone.txt' 
INTO TABLE broadleafcommerce.BLC_CUSTOMER_PHONE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(CUSTOMER_PHONE_ID, PHONE_NAME, CUSTOMER_ID, PHONE_ID);

DELETE FROM broadleafcommerce.BLC_PHONE;

LOAD DATA INFILE '@@BASE_DIR@@/phone.txt' 
INTO TABLE broadleafcommerce.BLC_PHONE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(PHONE_ID, PHONE_NUMBER, IS_ACTIVE, IS_DEFAULT);

DELETE FROM broadleafcommerce.BLC_CHALLENGE_QUESTION;

LOAD DATA INFILE '@@BASE_DIR@@/challenge_question.txt' 
INTO TABLE broadleafcommerce.BLC_CHALLENGE_QUESTION
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(QUESTION_ID, QUESTION);

DELETE FROM broadleafcommerce.BLC_PRODUCT_CROSS_SALE;

LOAD DATA INFILE '@@BASE_DIR@@/product_cross_sale.txt' 
INTO TABLE broadleafcommerce.BLC_PRODUCT_CROSS_SALE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(CROSS_SALE_PRODUCT_ID, PROMOTION_MESSAGE, SEQUENCE, PRODUCT_ID, RELATED_SALE_PRODUCT_ID);

DELETE FROM broadleafcommerce.BLC_PRODUCT_UP_SALE;

LOAD DATA INFILE '@@BASE_DIR@@/product_up_sale.txt' 
INTO TABLE broadleafcommerce.BLC_PRODUCT_UP_SALE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(UP_SALE_PRODUCT_ID, PROMOTION_MESSAGE, SEQUENCE, PRODUCT_ID, RELATED_SALE_PRODUCT_ID);

DELETE FROM broadleafcommerce.BLC_STORE;

LOAD DATA INFILE '@@BASE_DIR@@/store.txt' 
INTO TABLE broadleafcommerce.BLC_STORE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(STORE_ID, STORE_NAME, ADDRESS_1, ADDRESS_2, STORE_CITY, STORE_STATE, STORE_ZIP, LATITUDE, LONGITUDE);

DELETE FROM broadleafcommerce.BLC_ZIP_CODE;

LOAD DATA INFILE '@@BASE_DIR@@/zipCode.txt' 
INTO TABLE broadleafcommerce.BLC_ZIP_CODE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(ZIP_CODE_ID, ZIPCODE, ZIP_LATITUDE, ZIP_LONGITUDE);

DELETE FROM broadleafcommerce.BLC_PRODUCT_FEATURED;

LOAD DATA INFILE '@@BASE_DIR@@/product_featured.txt' 
INTO TABLE broadleafcommerce.BLC_PRODUCT_FEATURED
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(FEATURED_PRODUCT_ID, PROMOTION_MESSAGE, SEQUENCE, CATEGORY_ID, PRODUCT_ID);

DELETE FROM broadleafcommerce.BLC_CATEGORY_IMAGE;

LOAD DATA INFILE '@@BASE_DIR@@/category_image.txt' 
INTO TABLE broadleafcommerce.BLC_CATEGORY_IMAGE
FIELDS TERMINATED BY '|' ENCLOSED BY ""
(CATEGORY_ID, URL, NAME);

SET foreign_key_checks = 1;
